title: PLACEHOLDER

email: vlpyslaru+math@gmail.com
github_username:  "vladpy8"

url: "https://vladpy8.github.io"
baseurl: "/math"

description: >-
  PLACEHOLDER

include:
  - _pages

theme: minima
plugins:
  - jekyll-feed
